[phases.setup]
nixPkgs = ['python311', 'file', 'libmagic', 'pkg-config', 'gcc']

[phases.install]
cmds = [
    'pip install --upgrade pip setuptools wheel',
    'pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = 'python main.py'

[variables]
PYTHONPATH = '.'
PYTHONUNBUFFERED = '1'
PYTHONDONTWRITEBYTECODE = '1'