# Railway.com Deployment Configuration
# Using Nixpacks builder for Python 3.12.2 deployment
# Proper Railway-supported configuration

[build]
# Use Railway's Nixpacks builder
builder = "NIXPACKS"

# Watch patterns for automatic deployments
watchPatterns = ["**/*.py", "requirements.txt", "bot/**", "health_*.py", "main.py"]

# Nixpacks configuration using proper Railway format
[build.nixpacks]
providers = ["python"]

# Environment variables for build
[build.nixpacks.variables]
PYTHON_VERSION = "3.12.2"

# Build phases configuration using proper array-of-table format
[[build.nixpacks.phases]]
name = "setup"
# System packages required for python-magic and PyMuPDF
nixPkgs = ["file", "pkg-config", "gcc", "git", "zlib", "libffi", "openssl", "python3", "python3Packages.pip", "python3Packages.setuptools", "python3Packages.wheel"]

[[build.nixpacks.phases]]
name = "install"
dependsOn = ["setup"]
cmds = ["pip install --no-cache-dir --upgrade pip setuptools wheel", "pip install --no-cache-dir -r requirements.txt"]

[deploy]
# Start command for the Telegram bot (background worker)
startCommand = "python main.py"

# Restart policy for production reliability
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Graceful shutdown timing for proper cleanup
terminationGracePeriodSeconds = 30

# Note: No healthcheck configuration - this is a background worker, not a web service

# Environment-specific configurations
[environments.production]
[environments.production.deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.development]
[environments.development.deploy] 
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 2

# Environment variables for Railway deployment
[environments.production.variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONPATH = "."

[environments.development.variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONPATH = "."